# Use the official Airflow image as a base
FROM apache/airflow:2.5.1

# Switch to root user to install additional packages
# USER root

# Install joblib
RUN pip install joblib
RUN pip install scikit-learn

# Switch back to the airflow user
USER airflow